# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CKB's Stash
email: bensoncat99@gmail.com
description: "Notes, blogs, random posts about random things"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chenkb91.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  ChenKB91
motto: "What is life but a chaotic show? If you've got a cat, then you get a chaotic show with a cat, which makes everything justified."

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
google_analytics: G-Y072K5YWXX
disqus_shortname: chenkb

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->

# for faster re-render
# incremental: true

plugins:
  - jekyll-seo-tag